server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userservicedb
    useJDBCCompliantTimeZoneShift: true
    serverTimezone: UTC
    username: sa
    password: password

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.H2Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:h2:mem:userservicedb
    user: sa
    password: password

  h2:
    console:
      enabled: true

register_service:
  regex:
    validation:
      email: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}"
      password: "^.{6,}$"
      name: "[A-Za-z\\s-]{1,}"
  strings:
    email:
      content: "Вы успшено зарегистрированы в нашем сервисе!"
  timeouts:
    wait_thread_ms: 5000
  async_tasks_pool:
    size: 4